In [3]:
import numpy as np
a=np.arange(12).reshape(3,4)
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
for r in a.flat:
    print(r)


0
1
2
3
4
5
6
7
8
9
10
11


In [5]:
for r in a.flatten():
    print(r)
    

0
1
2
3
4
5
6
7
8
9
10
11


In [6]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
a[:,1]

array([1, 5, 9])

In [8]:
a[0,:]

array([0, 1, 2, 3])

In [9]:
b=np.arange(1,50,5)

In [10]:
b

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [11]:
b=np.arange(0,500,5)

In [12]:
b

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220, 225, 230, 235, 240, 245, 250, 255,
       260, 265, 270, 275, 280, 285, 290, 295, 300, 305, 310, 315, 320,
       325, 330, 335, 340, 345, 350, 355, 360, 365, 370, 375, 380, 385,
       390, 395, 400, 405, 410, 415, 420, 425, 430, 435, 440, 445, 450,
       455, 460, 465, 470, 475, 480, 485, 490, 495])

In [13]:
b.shape

(100,)

In [14]:
b.reshape(10,10)

array([[  0,   5,  10,  15,  20,  25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120, 125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170, 175, 180, 185, 190, 195],
       [200, 205, 210, 215, 220, 225, 230, 235, 240, 245],
       [250, 255, 260, 265, 270, 275, 280, 285, 290, 295],
       [300, 305, 310, 315, 320, 325, 330, 335, 340, 345],
       [350, 355, 360, 365, 370, 375, 380, 385, 390, 395],
       [400, 405, 410, 415, 420, 425, 430, 435, 440, 445],
       [450, 455, 460, 465, 470, 475, 480, 485, 490, 495]])

In [15]:
ratio=b[:,0]/5

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [16]:
b[:,0]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [17]:
b

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220, 225, 230, 235, 240, 245, 250, 255,
       260, 265, 270, 275, 280, 285, 290, 295, 300, 305, 310, 315, 320,
       325, 330, 335, 340, 345, 350, 355, 360, 365, 370, 375, 380, 385,
       390, 395, 400, 405, 410, 415, 420, 425, 430, 435, 440, 445, 450,
       455, 460, 465, 470, 475, 480, 485, 490, 495])

In [18]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
b.shape

(100,)

In [20]:
a.shape

(3, 4)

In [21]:
b=b.reshape(10,10)

In [22]:
b

array([[  0,   5,  10,  15,  20,  25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120, 125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170, 175, 180, 185, 190, 195],
       [200, 205, 210, 215, 220, 225, 230, 235, 240, 245],
       [250, 255, 260, 265, 270, 275, 280, 285, 290, 295],
       [300, 305, 310, 315, 320, 325, 330, 335, 340, 345],
       [350, 355, 360, 365, 370, 375, 380, 385, 390, 395],
       [400, 405, 410, 415, 420, 425, 430, 435, 440, 445],
       [450, 455, 460, 465, 470, 475, 480, 485, 490, 495]])

In [23]:
b.shape

(10, 10)

In [24]:
b[:,0]

array([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450])

In [25]:
ratio=b[:,0]/5

In [26]:
ratio

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [27]:
b=np.arange(0,100,5)

In [28]:
b

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [29]:
b=b.reshape(4,5)

In [30]:
b

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [31]:
good_num=b[:,1]>35

In [32]:
good_num

array([False, False,  True,  True])

In [33]:
gn=b[b[:,3]>60,3]

In [34]:
gn

array([65, 90])

In [35]:
b[:,1]

array([ 5, 30, 55, 80])